# Generated by Django 4.2.30 on 2026-05-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aksiya_id_alter_branch_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('old_price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='sets/')),
                ('is_active', models.BooleanField(default=True)),
                ('items_description', models.TextField(blank=True, default='', help_text='Set tarkibi (masalan: 8 Salmon Nigiri + 6 California Roll + 2x Choy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(default='+998901234567', max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(),
        ),
    ]
