# Generated by Django 4.2.30 on 2026-05-02 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_set_branch_phone_alter_meal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='calories',
            field=models.PositiveIntegerField(default=0, help_text='Kaloriya miqdori'),
        ),
        migrations.AddField(
            model_name='set',
            name='highlights',
            field=models.TextField(blank=True, default='', help_text='Alohida xususiyatlari (har qator bitta highlight)'),
        ),
        migrations.AddField(
            model_name='set',
            name='preparation_time',
            field=models.CharField(blank=True, default='', help_text='Tayyorlanish vaqti (masalan: 20-30 daqiqa)', max_length=50),
        ),
        migrations.AddField(
            model_name='set',
            name='servings',
            field=models.PositiveIntegerField(default=1, help_text='Nechta kishilik (1, 2, 4)'),
        ),
        migrations.AlterField(
            model_name='set',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sets/'),
        ),
        migrations.CreateModel(
            name='SetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sets/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.set')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
