# Generated by Django 4.2.30 on 2026-05-02 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_set_calories_set_highlights_set_preparation_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hudud nomi (masalan: Yunusabad, Chilanzar)', max_length=100)),
                ('min_order', models.PositiveIntegerField(default=0, help_text="Minimal buyurtma summasi (so'm)")),
                ('delivery_fee', models.PositiveIntegerField(default=0, help_text="Yetkazib berish narxi (so'm)")),
                ('estimated_time', models.CharField(default='30-45 daqiqa', help_text='Taxminiy yetkazib berish vaqti', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text="Qo'shimcha ma'lumot")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ko'rsatish tartibi")),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(blank=True, help_text="Telegram user ID (agar TelegramUser bo'lmasa)", null=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('telegram_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='core.telegramuser')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Foydalanuvchi'), ('cashier', 'Kassir')], max_length=20)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
