# Generated by Django 4.2.30 on 2026-05-03 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_deliveryzone_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bot_token',
            field=models.CharField(blank=True, default='', help_text='Filial uchun Telegram bot token (ixtiyoriy)', max_length=200),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Filial buyurtma qabul qiladimi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_chat_id',
            field=models.CharField(blank=True, default='', help_text='Manager Telegram chat ID (buyurtma bildirishnomasi uchun)', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.branch'),
        ),
    ]
